on:
  push:
    branches:
      - DEV
  workflow_dispatch:
name: Heroku Deployment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy server to root and commit
        run: |
          mv ./server/* ./
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Heroku Deployer
          author_email: heroku.deployer@ark-automate.com
          message: "heroku deployment commit"
          push: false
      - run: git config user.email "deployer@ark-automate.com" && git config user.name "deployBot" && git add -A && git commit -m "Updated code"
      - uses: akhileshns/heroku-deploy@v3.11.10
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ark-automate"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          dontuseforce: false
          branch: "DEV"
